### ISSUE TITLE
Allow all versions of action

### ISSUE THREAD

**Issue by j4m350n** [ActionsDesk/github-actions-allow-list-as-code-action#93]
Hello,

I work in Telenor and we are using this action. I am wondering if it is possible to allow an action with any version.

I.e.

Our `github-actions-allow-list.yml` looks like:

```yaml
actions:
  - ActionsDesk/github-actions-allow-list-as-code-action@v3.0.0
  - abc/abc@v1.2.3
  - def/def@v4.5.6
```

Is it also possible to allow an action like this?

```yaml
  - OurPublicSlug/abc
```

Without having to provide the version? Or `OurPublicSlug/abc@*` (at star) to allow all?

Thanks, James.

**Comment by j4m350n** [comment]
@theztefan Would you know?

**Comment by stoe** [comment]
> Is it also possible to allow an action like this?
> 
> ```yaml
>   - OurPublicSlug/abc
> ```
> 
> Without having to provide the version? Or `OurPublicSlug/abc@*` (at star) to allow all?

@j4m350n, yes that is possible, and as you pointed out it needs to be `OurPublicSlug/abc@*` to work for all versions.

Only patterns documented under https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#allowing-select-actions-and-reusable-workflows-to-run are possible.

**Comment by theztefan** [comment]
Hey @j4m350n! As @stoe point out, technically, the feature (and therefore this Action) does allow `*` wildcard character which makes your request possible. [Reference to wildcard matching](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

That being said, you would still want to check in and confirm your company policy allows this.
